namespace ClassFramework.TemplateFramework.Templates;

public sealed class CodeGenerationHeaderTemplate : CsharpClassGeneratorBase<CsharpClassGeneratorSettings>, IStringBuilderTemplate
{
    public string Version
        => !string.IsNullOrEmpty(Model?.EnvironmentVersion)
            ? Model.EnvironmentVersion
            : Environment.Version.ToString();

    public void Render(StringBuilder builder)
    {
        Guard.IsNotNull(builder);
        Guard.IsNotNull(Model);

        if (!Model.CreateCodeGenerationHeader)
        {
            return;
        }

        builder.AppendLine(Model.CultureInfo, $$"""
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: {{Version}}
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
""");
    }
}
