global using System;
global using System.Collections.Generic;
global using System.ComponentModel.DataAnnotations;
global using System.Linq;
global using FluentAssertions;
global using ModelFramework.Common.Contracts;
global using ModelFramework.Common.Extensions;
global using ModelFramework.Common.Tests.TestFixtures;
global using Xunit;
