// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 7.0.10
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ModelFramework.Objects.Models
{
#nullable enable
    public partial class OverloadModel
    {
        public string MethodName
        {
            get;
            set;
        }

        public string InitializeExpression
        {
            get;
            set;
        }

        public System.Collections.Generic.List<ModelFramework.Objects.Models.ParameterModel> Parameters
        {
            get;
            set;
        }

        public ModelFramework.Objects.Contracts.IOverload ToEntity()
        {
            #pragma warning disable CS8604 // Possible null reference argument.
            #pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
            return new ModelFramework.Objects.Overload(MethodName, InitializeExpression, Parameters.Select(x => x.ToEntity()));
            #pragma warning restore CS8600 // Converting null literal or possible null value to non-nullable type.
            #pragma warning restore CS8604 // Possible null reference argument.
        }

        public OverloadModel()
        {
            Parameters = new System.Collections.Generic.List<ModelFramework.Objects.Models.ParameterModel>();
            #pragma warning disable CS8603 // Possible null reference return.
            MethodName = string.Empty;
            InitializeExpression = string.Empty;
            #pragma warning restore CS8603 // Possible null reference return.
        }

        public OverloadModel(ModelFramework.Objects.Contracts.IOverload source)
        {
            Parameters = new System.Collections.Generic.List<ModelFramework.Objects.Models.ParameterModel>();
            MethodName = source.MethodName;
            InitializeExpression = source.InitializeExpression;
            Parameters.AddRange(source.Parameters.Select(x => new ModelFramework.Objects.Models.ParameterModel(x)));
        }
    }
#nullable restore
}
