// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.3
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ModelFramework.Database.Builders
{
#nullable enable
    public partial class SchemaBuilder
    {
        public System.Collections.Generic.List<ModelFramework.Database.Builders.TableBuilder> Tables
        {
            get;
            set;
        }

        public System.Collections.Generic.List<ModelFramework.Database.Builders.StoredProcedureBuilder> StoredProcedures
        {
            get;
            set;
        }

        public System.Collections.Generic.List<ModelFramework.Database.Builders.ViewBuilder> Views
        {
            get;
            set;
        }

        public string Name
        {
            get
            {
                return _nameDelegate.Value;
            }
            set
            {
                _nameDelegate = new (() => value);
            }
        }

        public System.Collections.Generic.List<ModelFramework.Common.Builders.MetadataBuilder> Metadata
        {
            get;
            set;
        }

        public SchemaBuilder AddMetadata(System.Collections.Generic.IEnumerable<ModelFramework.Common.Builders.MetadataBuilder> metadata)
        {
            return AddMetadata(metadata.ToArray());
        }

        public SchemaBuilder AddMetadata(params ModelFramework.Common.Builders.MetadataBuilder[] metadata)
        {
            Metadata.AddRange(metadata);
            return this;
        }

        public SchemaBuilder AddMetadata(string name, object? value)
        {
            AddMetadata(new ModelFramework.Common.Builders.MetadataBuilder().WithName(name).WithValue(value));
            return this;
        }

        public SchemaBuilder AddStoredProcedures(System.Collections.Generic.IEnumerable<ModelFramework.Database.Builders.StoredProcedureBuilder> storedProcedures)
        {
            return AddStoredProcedures(storedProcedures.ToArray());
        }

        public SchemaBuilder AddStoredProcedures(params ModelFramework.Database.Builders.StoredProcedureBuilder[] storedProcedures)
        {
            StoredProcedures.AddRange(storedProcedures);
            return this;
        }

        public SchemaBuilder AddTables(System.Collections.Generic.IEnumerable<ModelFramework.Database.Builders.TableBuilder> tables)
        {
            return AddTables(tables.ToArray());
        }

        public SchemaBuilder AddTables(params ModelFramework.Database.Builders.TableBuilder[] tables)
        {
            Tables.AddRange(tables);
            return this;
        }

        public SchemaBuilder AddViews(System.Collections.Generic.IEnumerable<ModelFramework.Database.Builders.ViewBuilder> views)
        {
            return AddViews(views.ToArray());
        }

        public SchemaBuilder AddViews(params ModelFramework.Database.Builders.ViewBuilder[] views)
        {
            Views.AddRange(views);
            return this;
        }

        public ModelFramework.Database.Contracts.ISchema Build()
        {
            return new ModelFramework.Database.Schema(Tables.Select(x => x.Build()), StoredProcedures.Select(x => x.Build()), Views.Select(x => x.Build()), Name, Metadata.Select(x => x.Build()));
        }

        public SchemaBuilder WithName(string name)
        {
            Name = name;
            return this;
        }

        public SchemaBuilder WithName(System.Func<string> nameDelegate)
        {
            _nameDelegate = new (nameDelegate);
            return this;
        }

        public SchemaBuilder()
        {
            Tables = new System.Collections.Generic.List<ModelFramework.Database.Builders.TableBuilder>();
            StoredProcedures = new System.Collections.Generic.List<ModelFramework.Database.Builders.StoredProcedureBuilder>();
            Views = new System.Collections.Generic.List<ModelFramework.Database.Builders.ViewBuilder>();
            Metadata = new System.Collections.Generic.List<ModelFramework.Common.Builders.MetadataBuilder>();
            _nameDelegate = new (() => string.Empty);
        }

        public SchemaBuilder(ModelFramework.Database.Contracts.ISchema source)
        {
            Tables = new System.Collections.Generic.List<ModelFramework.Database.Builders.TableBuilder>();
            StoredProcedures = new System.Collections.Generic.List<ModelFramework.Database.Builders.StoredProcedureBuilder>();
            Views = new System.Collections.Generic.List<ModelFramework.Database.Builders.ViewBuilder>();
            Metadata = new System.Collections.Generic.List<ModelFramework.Common.Builders.MetadataBuilder>();
            Tables.AddRange(source.Tables.Select(x => new ModelFramework.Database.Builders.TableBuilder(x)));
            StoredProcedures.AddRange(source.StoredProcedures.Select(x => new ModelFramework.Database.Builders.StoredProcedureBuilder(x)));
            Views.AddRange(source.Views.Select(x => new ModelFramework.Database.Builders.ViewBuilder(x)));
            _nameDelegate = new (() => source.Name);
            Metadata.AddRange(source.Metadata.Select(x => new ModelFramework.Common.Builders.MetadataBuilder(x)));
        }

        private System.Lazy<string> _nameDelegate;
    }
#nullable restore
}

