// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using ModelFramework.Objects.Builders;
using ModelFramework.Objects.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ModelFramework.CodeGeneration.Tests.CodeGenerationProviders
{
#nullable enable
    public partial class ModelFrameworkCSharpClassBase
    {
        protected static ITypeBase[] GetObjectsModels()
        {
            return new[]
            {
                new ClassBuilder()
                    .WithNamespace(@"ModelFramework.Objects.Contracts")
                    .AddInterfaces(
                        @"ModelFramework.Common.Contracts.IMetadataContainer",
                        @"ModelFramework.Common.Contracts.INameContainer")
                    .AddProperties(
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Parameters")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Objects.Contracts.IAttributeParameter, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Metadata")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Common.Contracts.IMetadata, ModelFramework.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Name")
                            .WithTypeName(@"System.String"))
                    .WithName(@"IAttribute"),
                new ClassBuilder()
                    .WithNamespace(@"ModelFramework.Objects.Contracts")
                    .AddInterfaces(
                        @"ModelFramework.Common.Contracts.IMetadataContainer",
                        @"ModelFramework.Common.Contracts.INameContainer")
                    .AddProperties(
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Value")
                            .WithTypeName(@"System.Object"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Metadata")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Common.Contracts.IMetadata, ModelFramework.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Name")
                            .WithTypeName(@"System.String"))
                    .WithName(@"IAttributeParameter"),
                new ClassBuilder()
                    .WithNamespace(@"ModelFramework.Objects.Contracts")
                    .AddInterfaces(
                        @"ModelFramework.Objects.Contracts.ITypeBase",
                        @"ModelFramework.Common.Contracts.IMetadataContainer",
                        @"ModelFramework.Objects.Contracts.IVisibilityContainer",
                        @"ModelFramework.Common.Contracts.INameContainer",
                        @"ModelFramework.Objects.Contracts.IAttributesContainer",
                        @"ModelFramework.Objects.Contracts.IEnumsContainer")
                    .AddProperties(
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Fields")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Objects.Contracts.IClassField, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Static")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Sealed")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"SubClasses")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Objects.Contracts.IClass, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Constructors")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Objects.Contracts.IClassConstructor, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"BaseClass")
                            .WithTypeName(@"System.String"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Record")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Namespace")
                            .WithTypeName(@"System.String"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Partial")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Interfaces")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Properties")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Objects.Contracts.IClassProperty, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Methods")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Objects.Contracts.IClassMethod, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"GenericTypeArguments")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"GenericTypeArgumentConstraints")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Metadata")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Common.Contracts.IMetadata, ModelFramework.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Visibility")
                            .WithTypeName(@"ModelFramework.Objects.Contracts.Visibility"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Name")
                            .WithTypeName(@"System.String"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Attributes")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Objects.Contracts.IAttribute, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Enums")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Objects.Contracts.IEnum, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"))
                    .WithName(@"IClass"),
                new ClassBuilder()
                    .WithNamespace(@"ModelFramework.Objects.Contracts")
                    .AddInterfaces(
                        @"ModelFramework.Common.Contracts.IMetadataContainer",
                        @"ModelFramework.Objects.Contracts.IExtendedVisibilityContainer",
                        @"ModelFramework.Objects.Contracts.IVisibilityContainer",
                        @"ModelFramework.Objects.Contracts.IAttributesContainer",
                        @"ModelFramework.Objects.Contracts.ICodeStatementsContainer",
                        @"ModelFramework.Objects.Contracts.IParametersContainer")
                    .AddProperties(
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"ChainCall")
                            .WithTypeName(@"System.String"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Metadata")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Common.Contracts.IMetadata, ModelFramework.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Static")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Virtual")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Abstract")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Protected")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Override")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Visibility")
                            .WithTypeName(@"ModelFramework.Objects.Contracts.Visibility"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Attributes")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Objects.Contracts.IAttribute, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"CodeStatements")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Objects.Contracts.ICodeStatement, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Parameters")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Objects.Contracts.IParameter, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"))
                    .WithName(@"IClassConstructor"),
                new ClassBuilder()
                    .WithNamespace(@"ModelFramework.Objects.Contracts")
                    .AddInterfaces(
                        @"ModelFramework.Common.Contracts.IMetadataContainer",
                        @"ModelFramework.Objects.Contracts.IExtendedVisibilityContainer",
                        @"ModelFramework.Objects.Contracts.IVisibilityContainer",
                        @"ModelFramework.Common.Contracts.INameContainer",
                        @"ModelFramework.Objects.Contracts.IAttributesContainer",
                        @"ModelFramework.Objects.Contracts.ITypeContainer",
                        @"ModelFramework.Common.Contracts.IDefaultValueContainer")
                    .AddProperties(
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"ReadOnly")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Constant")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Event")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Metadata")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Common.Contracts.IMetadata, ModelFramework.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Static")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Virtual")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Abstract")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Protected")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Override")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Visibility")
                            .WithTypeName(@"ModelFramework.Objects.Contracts.Visibility"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Name")
                            .WithTypeName(@"System.String"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Attributes")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Objects.Contracts.IAttribute, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"TypeName")
                            .WithTypeName(@"System.String"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"IsNullable")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"DefaultValue")
                            .WithTypeName(@"System.Object")
                            .WithIsNullable(true))
                    .WithName(@"IClassField"),
                new ClassBuilder()
                    .WithNamespace(@"ModelFramework.Objects.Contracts")
                    .AddInterfaces(
                        @"ModelFramework.Common.Contracts.IMetadataContainer",
                        @"ModelFramework.Objects.Contracts.IExtendedVisibilityContainer",
                        @"ModelFramework.Objects.Contracts.IVisibilityContainer",
                        @"ModelFramework.Common.Contracts.INameContainer",
                        @"ModelFramework.Objects.Contracts.IAttributesContainer",
                        @"ModelFramework.Objects.Contracts.ICodeStatementsContainer",
                        @"ModelFramework.Objects.Contracts.IParametersContainer",
                        @"ModelFramework.Objects.Contracts.ITypeContainer",
                        @"ModelFramework.Objects.Contracts.IExplicitInterfaceNameContainer")
                    .AddProperties(
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Partial")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"ExtensionMethod")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Operator")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"GenericTypeArguments")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"GenericTypeArgumentConstraints")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Metadata")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Common.Contracts.IMetadata, ModelFramework.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Static")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Virtual")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Abstract")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Protected")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Override")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Visibility")
                            .WithTypeName(@"ModelFramework.Objects.Contracts.Visibility"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Name")
                            .WithTypeName(@"System.String"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Attributes")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Objects.Contracts.IAttribute, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"CodeStatements")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Objects.Contracts.ICodeStatement, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Parameters")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Objects.Contracts.IParameter, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"TypeName")
                            .WithTypeName(@"System.String"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"IsNullable")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"ExplicitInterfaceName")
                            .WithTypeName(@"System.String"))
                    .WithName(@"IClassMethod"),
                new ClassBuilder()
                    .WithNamespace(@"ModelFramework.Objects.Contracts")
                    .AddInterfaces(
                        @"ModelFramework.Common.Contracts.IMetadataContainer",
                        @"ModelFramework.Objects.Contracts.IExtendedVisibilityContainer",
                        @"ModelFramework.Objects.Contracts.IVisibilityContainer",
                        @"ModelFramework.Common.Contracts.INameContainer",
                        @"ModelFramework.Objects.Contracts.IAttributesContainer",
                        @"ModelFramework.Objects.Contracts.ITypeContainer",
                        @"ModelFramework.Objects.Contracts.IExplicitInterfaceNameContainer")
                    .AddProperties(
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"HasGetter")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"HasSetter")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"HasInitializer")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"GetterVisibility")
                            .WithTypeName(@"System.Nullable`1[[ModelFramework.Objects.Contracts.Visibility, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]")
                            .WithIsNullable(true),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"SetterVisibility")
                            .WithTypeName(@"System.Nullable`1[[ModelFramework.Objects.Contracts.Visibility, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]")
                            .WithIsNullable(true),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"InitializerVisibility")
                            .WithTypeName(@"System.Nullable`1[[ModelFramework.Objects.Contracts.Visibility, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]")
                            .WithIsNullable(true),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"GetterCodeStatements")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Objects.Contracts.ICodeStatement, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"SetterCodeStatements")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Objects.Contracts.ICodeStatement, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"InitializerCodeStatements")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Objects.Contracts.ICodeStatement, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Metadata")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Common.Contracts.IMetadata, ModelFramework.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Static")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Virtual")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Abstract")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Protected")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Override")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Visibility")
                            .WithTypeName(@"ModelFramework.Objects.Contracts.Visibility"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Name")
                            .WithTypeName(@"System.String"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Attributes")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Objects.Contracts.IAttribute, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"TypeName")
                            .WithTypeName(@"System.String"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"IsNullable")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"ExplicitInterfaceName")
                            .WithTypeName(@"System.String"))
                    .WithName(@"IClassProperty"),
                new ClassBuilder()
                    .WithNamespace(@"ModelFramework.Objects.Contracts")
                    .AddInterfaces(
                        @"ModelFramework.Objects.Contracts.IAttributesContainer",
                        @"ModelFramework.Common.Contracts.IMetadataContainer",
                        @"ModelFramework.Common.Contracts.INameContainer",
                        @"ModelFramework.Objects.Contracts.IVisibilityContainer")
                    .AddProperties(
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Members")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Objects.Contracts.IEnumMember, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Attributes")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Objects.Contracts.IAttribute, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Metadata")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Common.Contracts.IMetadata, ModelFramework.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Name")
                            .WithTypeName(@"System.String"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Visibility")
                            .WithTypeName(@"ModelFramework.Objects.Contracts.Visibility"))
                    .WithName(@"IEnum"),
                new ClassBuilder()
                    .WithNamespace(@"ModelFramework.Objects.Contracts")
                    .AddInterfaces(
                        @"ModelFramework.Objects.Contracts.IAttributesContainer",
                        @"ModelFramework.Common.Contracts.INameContainer",
                        @"ModelFramework.Common.Contracts.IMetadataContainer")
                    .AddProperties(
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Value")
                            .WithTypeName(@"System.Object")
                            .WithIsNullable(true),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Attributes")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Objects.Contracts.IAttribute, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Name")
                            .WithTypeName(@"System.String"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Metadata")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Common.Contracts.IMetadata, ModelFramework.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"))
                    .WithName(@"IEnumMember"),
                new ClassBuilder()
                    .WithNamespace(@"ModelFramework.Objects.Contracts")
                    .AddInterfaces(
                        @"ModelFramework.Objects.Contracts.ITypeBase",
                        @"ModelFramework.Common.Contracts.IMetadataContainer",
                        @"ModelFramework.Objects.Contracts.IVisibilityContainer",
                        @"ModelFramework.Common.Contracts.INameContainer",
                        @"ModelFramework.Objects.Contracts.IAttributesContainer")
                    .AddProperties(
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Namespace")
                            .WithTypeName(@"System.String"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Partial")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Interfaces")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Properties")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Objects.Contracts.IClassProperty, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Methods")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Objects.Contracts.IClassMethod, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"GenericTypeArguments")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"GenericTypeArgumentConstraints")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Metadata")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Common.Contracts.IMetadata, ModelFramework.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Visibility")
                            .WithTypeName(@"ModelFramework.Objects.Contracts.Visibility"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Name")
                            .WithTypeName(@"System.String"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Attributes")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Objects.Contracts.IAttribute, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"))
                    .WithName(@"IInterface"),
                new ClassBuilder()
                    .WithNamespace(@"ModelFramework.Objects.Contracts")
                    .AddInterfaces(
                        @"ModelFramework.Objects.Contracts.ITypeContainer",
                        @"ModelFramework.Objects.Contracts.IAttributesContainer",
                        @"ModelFramework.Common.Contracts.IMetadataContainer",
                        @"ModelFramework.Common.Contracts.INameContainer",
                        @"ModelFramework.Common.Contracts.IDefaultValueContainer")
                    .AddProperties(
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"IsParamArray")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"IsOut")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"IsRef")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"TypeName")
                            .WithTypeName(@"System.String"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"IsNullable")
                            .WithTypeName(@"System.Boolean"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Attributes")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Objects.Contracts.IAttribute, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Metadata")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Common.Contracts.IMetadata, ModelFramework.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Name")
                            .WithTypeName(@"System.String"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"DefaultValue")
                            .WithTypeName(@"System.Object")
                            .WithIsNullable(true))
                    .WithName(@"IParameter"),
            }.Select(x => x.Build()).ToArray();
        }
    }
#nullable restore
}

