// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.1
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using ModelFramework.Objects.Builders;
using ModelFramework.Objects.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ModelFramework.CodeGeneration.Tests.CodeGenerationProviders
{
#nullable enable
    public partial class ModelFrameworkCSharpClassBase
    {
        protected static ITypeBase[] GetModels()
        {
            return new[]
            {
                new ClassBuilder
                {
                    Namespace = @"ModelFramework.Objects.Contracts",
                    Interfaces = new List<string>(new[]
                    {
                        @"ModelFramework.Common.Contracts.IMetadataContainer",
                        @"ModelFramework.Common.Contracts.INameContainer",
                    } ),
                    Properties = new List<ClassPropertyBuilder>(new[]
                    {
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Parameters",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Objects.Contracts.IAttributeParameter, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Metadata",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Common.Contracts.IMetadata, ModelFramework.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Name",
                            TypeName = @"System.String",
                        },
                    } ),
                    Name = @"IAttribute",
                },
                new ClassBuilder
                {
                    Namespace = @"ModelFramework.Objects.Contracts",
                    Interfaces = new List<string>(new[]
                    {
                        @"ModelFramework.Common.Contracts.IMetadataContainer",
                        @"ModelFramework.Common.Contracts.INameContainer",
                    } ),
                    Properties = new List<ClassPropertyBuilder>(new[]
                    {
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Value",
                            TypeName = @"System.Object",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Metadata",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Common.Contracts.IMetadata, ModelFramework.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Name",
                            TypeName = @"System.String",
                        },
                    } ),
                    Name = @"IAttributeParameter",
                },
                new ClassBuilder
                {
                    Namespace = @"ModelFramework.Objects.Contracts",
                    Interfaces = new List<string>(new[]
                    {
                        @"ModelFramework.Objects.Contracts.ITypeBase",
                        @"ModelFramework.Common.Contracts.IMetadataContainer",
                        @"ModelFramework.Objects.Contracts.IVisibilityContainer",
                        @"ModelFramework.Common.Contracts.INameContainer",
                        @"ModelFramework.Objects.Contracts.IAttributesContainer",
                        @"ModelFramework.Objects.Contracts.IEnumsContainer",
                    } ),
                    Properties = new List<ClassPropertyBuilder>(new[]
                    {
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Fields",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Objects.Contracts.IClassField, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Static",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Sealed",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"SubClasses",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Objects.Contracts.IClass, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Constructors",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Objects.Contracts.IClassConstructor, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"BaseClass",
                            TypeName = @"System.String",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Record",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Namespace",
                            TypeName = @"System.String",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Partial",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Interfaces",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Properties",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Objects.Contracts.IClassProperty, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Methods",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Objects.Contracts.IClassMethod, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"GenericTypeArguments",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"GenericTypeArgumentConstraints",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Metadata",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Common.Contracts.IMetadata, ModelFramework.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Visibility",
                            TypeName = @"ModelFramework.Objects.Contracts.Visibility",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Name",
                            TypeName = @"System.String",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Attributes",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Objects.Contracts.IAttribute, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Enums",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Objects.Contracts.IEnum, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                    } ),
                    Name = @"IClass",
                },
                new ClassBuilder
                {
                    Namespace = @"ModelFramework.Objects.Contracts",
                    Interfaces = new List<string>(new[]
                    {
                        @"ModelFramework.Common.Contracts.IMetadataContainer",
                        @"ModelFramework.Objects.Contracts.IExtendedVisibilityContainer",
                        @"ModelFramework.Objects.Contracts.IVisibilityContainer",
                        @"ModelFramework.Objects.Contracts.IAttributesContainer",
                        @"ModelFramework.Objects.Contracts.ICodeStatementsContainer",
                        @"ModelFramework.Objects.Contracts.IParametersContainer",
                    } ),
                    Properties = new List<ClassPropertyBuilder>(new[]
                    {
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"ChainCall",
                            TypeName = @"System.String",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Metadata",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Common.Contracts.IMetadata, ModelFramework.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Static",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Virtual",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Abstract",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Protected",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Override",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Visibility",
                            TypeName = @"ModelFramework.Objects.Contracts.Visibility",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Attributes",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Objects.Contracts.IAttribute, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"CodeStatements",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Objects.Contracts.ICodeStatement, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Parameters",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Objects.Contracts.IParameter, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                    } ),
                    Name = @"IClassConstructor",
                },
                new ClassBuilder
                {
                    Namespace = @"ModelFramework.Objects.Contracts",
                    Interfaces = new List<string>(new[]
                    {
                        @"ModelFramework.Common.Contracts.IMetadataContainer",
                        @"ModelFramework.Objects.Contracts.IExtendedVisibilityContainer",
                        @"ModelFramework.Objects.Contracts.IVisibilityContainer",
                        @"ModelFramework.Common.Contracts.INameContainer",
                        @"ModelFramework.Objects.Contracts.IAttributesContainer",
                        @"ModelFramework.Objects.Contracts.ITypeContainer",
                        @"ModelFramework.Common.Contracts.IDefaultValueContainer",
                    } ),
                    Properties = new List<ClassPropertyBuilder>(new[]
                    {
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"ReadOnly",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Constant",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Event",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Metadata",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Common.Contracts.IMetadata, ModelFramework.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Static",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Virtual",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Abstract",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Protected",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Override",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Visibility",
                            TypeName = @"ModelFramework.Objects.Contracts.Visibility",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Name",
                            TypeName = @"System.String",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Attributes",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Objects.Contracts.IAttribute, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"TypeName",
                            TypeName = @"System.String",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"IsNullable",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"DefaultValue",
                            TypeName = @"System.Object",
                            IsNullable = true,
                        },
                    } ),
                    Name = @"IClassField",
                },
                new ClassBuilder
                {
                    Namespace = @"ModelFramework.Objects.Contracts",
                    Interfaces = new List<string>(new[]
                    {
                        @"ModelFramework.Common.Contracts.IMetadataContainer",
                        @"ModelFramework.Objects.Contracts.IExtendedVisibilityContainer",
                        @"ModelFramework.Objects.Contracts.IVisibilityContainer",
                        @"ModelFramework.Common.Contracts.INameContainer",
                        @"ModelFramework.Objects.Contracts.IAttributesContainer",
                        @"ModelFramework.Objects.Contracts.ICodeStatementsContainer",
                        @"ModelFramework.Objects.Contracts.IParametersContainer",
                        @"ModelFramework.Objects.Contracts.ITypeContainer",
                        @"ModelFramework.Objects.Contracts.IExplicitInterfaceNameContainer",
                    } ),
                    Properties = new List<ClassPropertyBuilder>(new[]
                    {
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Partial",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"ExtensionMethod",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Operator",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"GenericTypeArguments",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"GenericTypeArgumentConstraints",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Metadata",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Common.Contracts.IMetadata, ModelFramework.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Static",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Virtual",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Abstract",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Protected",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Override",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Visibility",
                            TypeName = @"ModelFramework.Objects.Contracts.Visibility",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Name",
                            TypeName = @"System.String",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Attributes",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Objects.Contracts.IAttribute, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"CodeStatements",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Objects.Contracts.ICodeStatement, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Parameters",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Objects.Contracts.IParameter, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"TypeName",
                            TypeName = @"System.String",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"IsNullable",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"ExplicitInterfaceName",
                            TypeName = @"System.String",
                        },
                    } ),
                    Name = @"IClassMethod",
                },
                new ClassBuilder
                {
                    Namespace = @"ModelFramework.Objects.Contracts",
                    Interfaces = new List<string>(new[]
                    {
                        @"ModelFramework.Common.Contracts.IMetadataContainer",
                        @"ModelFramework.Objects.Contracts.IExtendedVisibilityContainer",
                        @"ModelFramework.Objects.Contracts.IVisibilityContainer",
                        @"ModelFramework.Common.Contracts.INameContainer",
                        @"ModelFramework.Objects.Contracts.IAttributesContainer",
                        @"ModelFramework.Objects.Contracts.ITypeContainer",
                        @"ModelFramework.Objects.Contracts.IExplicitInterfaceNameContainer",
                    } ),
                    Properties = new List<ClassPropertyBuilder>(new[]
                    {
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"HasGetter",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"HasSetter",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"HasInitializer",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"GetterVisibility",
                            TypeName = @"System.Nullable`1[[ModelFramework.Objects.Contracts.Visibility, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                            IsNullable = true,
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"SetterVisibility",
                            TypeName = @"System.Nullable`1[[ModelFramework.Objects.Contracts.Visibility, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                            IsNullable = true,
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"InitializerVisibility",
                            TypeName = @"System.Nullable`1[[ModelFramework.Objects.Contracts.Visibility, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                            IsNullable = true,
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"GetterCodeStatements",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Objects.Contracts.ICodeStatement, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"SetterCodeStatements",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Objects.Contracts.ICodeStatement, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"InitializerCodeStatements",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Objects.Contracts.ICodeStatement, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Metadata",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Common.Contracts.IMetadata, ModelFramework.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Static",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Virtual",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Abstract",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Protected",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Override",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Visibility",
                            TypeName = @"ModelFramework.Objects.Contracts.Visibility",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Name",
                            TypeName = @"System.String",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Attributes",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Objects.Contracts.IAttribute, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"TypeName",
                            TypeName = @"System.String",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"IsNullable",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"ExplicitInterfaceName",
                            TypeName = @"System.String",
                        },
                    } ),
                    Name = @"IClassProperty",
                },
                new ClassBuilder
                {
                    Namespace = @"ModelFramework.Objects.Contracts",
                    Interfaces = new List<string>(new[]
                    {
                        @"ModelFramework.Objects.Contracts.IAttributesContainer",
                        @"ModelFramework.Common.Contracts.IMetadataContainer",
                        @"ModelFramework.Common.Contracts.INameContainer",
                        @"ModelFramework.Objects.Contracts.IVisibilityContainer",
                    } ),
                    Properties = new List<ClassPropertyBuilder>(new[]
                    {
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Members",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Objects.Contracts.IEnumMember, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Attributes",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Objects.Contracts.IAttribute, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Metadata",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Common.Contracts.IMetadata, ModelFramework.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Name",
                            TypeName = @"System.String",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Visibility",
                            TypeName = @"ModelFramework.Objects.Contracts.Visibility",
                        },
                    } ),
                    Name = @"IEnum",
                },
                new ClassBuilder
                {
                    Namespace = @"ModelFramework.Objects.Contracts",
                    Interfaces = new List<string>(new[]
                    {
                        @"ModelFramework.Objects.Contracts.IAttributesContainer",
                        @"ModelFramework.Common.Contracts.INameContainer",
                        @"ModelFramework.Common.Contracts.IMetadataContainer",
                    } ),
                    Properties = new List<ClassPropertyBuilder>(new[]
                    {
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Value",
                            TypeName = @"System.Object",
                            IsNullable = true,
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Attributes",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Objects.Contracts.IAttribute, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Name",
                            TypeName = @"System.String",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Metadata",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Common.Contracts.IMetadata, ModelFramework.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                    } ),
                    Name = @"IEnumMember",
                },
                new ClassBuilder
                {
                    Namespace = @"ModelFramework.Objects.Contracts",
                    Interfaces = new List<string>(new[]
                    {
                        @"ModelFramework.Objects.Contracts.ITypeBase",
                        @"ModelFramework.Common.Contracts.IMetadataContainer",
                        @"ModelFramework.Objects.Contracts.IVisibilityContainer",
                        @"ModelFramework.Common.Contracts.INameContainer",
                        @"ModelFramework.Objects.Contracts.IAttributesContainer",
                    } ),
                    Properties = new List<ClassPropertyBuilder>(new[]
                    {
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Namespace",
                            TypeName = @"System.String",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Partial",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Interfaces",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Properties",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Objects.Contracts.IClassProperty, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Methods",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Objects.Contracts.IClassMethod, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"GenericTypeArguments",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"GenericTypeArgumentConstraints",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Metadata",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Common.Contracts.IMetadata, ModelFramework.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Visibility",
                            TypeName = @"ModelFramework.Objects.Contracts.Visibility",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Name",
                            TypeName = @"System.String",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Attributes",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Objects.Contracts.IAttribute, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                    } ),
                    Name = @"IInterface",
                },
                new ClassBuilder
                {
                    Namespace = @"ModelFramework.Objects.Contracts",
                    Interfaces = new List<string>(new[]
                    {
                        @"ModelFramework.Objects.Contracts.ITypeContainer",
                        @"ModelFramework.Objects.Contracts.IAttributesContainer",
                        @"ModelFramework.Common.Contracts.IMetadataContainer",
                        @"ModelFramework.Common.Contracts.INameContainer",
                        @"ModelFramework.Common.Contracts.IDefaultValueContainer",
                    } ),
                    Properties = new List<ClassPropertyBuilder>(new[]
                    {
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"IsParamArray",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"TypeName",
                            TypeName = @"System.String",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"IsNullable",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Attributes",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Objects.Contracts.IAttribute, ModelFramework.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Metadata",
                            TypeName = @"CrossCutting.Common.ValueCollection`1[[ModelFramework.Common.Contracts.IMetadata, ModelFramework.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Name",
                            TypeName = @"System.String",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"DefaultValue",
                            TypeName = @"System.Object",
                            IsNullable = true,
                        },
                    } ),
                    Name = @"IParameter",
                },
            }.Select(x => x.Build()).ToArray();
        }
    }
#nullable restore
}
