// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.6
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using ModelFramework.Objects.Builders;
using ModelFramework.Objects.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ModelFramework.CodeGeneration.Tests.CodeGenerationProviders
{
#nullable enable
    public partial class TestCSharpClassBase
    {
        protected static ITypeBase[] GetTestModels()
        {
            return new[]
            {
                new InterfaceBuilder()
                    .WithNamespace(@"ModelFramework.Common.Tests.Test.Contracts")
                    .AddProperties(
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"ChildProperty")
                            .WithTypeName(@"System.String"))
                    .WithName(@"IChild"),
                new InterfaceBuilder()
                    .WithNamespace(@"ModelFramework.Common.Tests.Test.Contracts")
                    .AddProperties(
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"ParentProperty")
                            .WithTypeName(@"System.String"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Child")
                            .WithTypeName(@"ModelFramework.Common.Tests.Test.Contracts.IChild"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Children")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[ModelFramework.Common.Tests.Test.Contracts.IChild, ModelFramework.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"))
                    .WithName(@"IParent"),
            }.Select(x => x.Build()).ToArray();
        }
    }
#nullable restore
}

