// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 7.0.4
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ModelFramework.Database.SqlStatements.Builders
{
#nullable enable
    public partial class LiteralSqlStatementBuilder : ModelFramework.Database.Contracts.ISqlStatementBuilder
    {
        public System.Text.StringBuilder Statement
        {
            get
            {
                return _statementDelegate.Value;
            }
            set
            {
                _statementDelegate = new (() => value);
            }
        }

        public System.Collections.Generic.List<ModelFramework.Common.Builders.MetadataBuilder> Metadata
        {
            get;
            set;
        }

        public ModelFramework.Database.Contracts.ISqlStatement Build()
        {
            #pragma warning disable CS8604 // Possible null reference argument.
            return new ModelFramework.Database.SqlStatements.LiteralSqlStatement(Statement?.ToString(), Metadata.Select(x => x.Build()));
            #pragma warning restore CS8604 // Possible null reference argument.
        }

        public LiteralSqlStatementBuilder WithStatement(System.Text.StringBuilder statement)
        {
            Statement = statement;
            return this;
        }

        public LiteralSqlStatementBuilder WithStatement(System.Func<System.Text.StringBuilder> statementDelegate)
        {
            _statementDelegate = new (statementDelegate);
            return this;
        }

        public LiteralSqlStatementBuilder WithStatement(string value)
        {
            if (Statement == null)
                Statement = new System.Text.StringBuilder();
            Statement.Clear().Append(value);
            return this;
        }

        public LiteralSqlStatementBuilder AppendToStatement(string value)
        {
            if (Statement == null)
                Statement = new System.Text.StringBuilder();
            Statement.Append(value);
            return this;
        }

        public LiteralSqlStatementBuilder AppendLineToStatement(string value)
        {
            if (Statement == null)
                Statement = new System.Text.StringBuilder();
            Statement.AppendLine(value);
            return this;
        }

        public LiteralSqlStatementBuilder AddMetadata(System.Collections.Generic.IEnumerable<ModelFramework.Common.Builders.MetadataBuilder> metadata)
        {
            return AddMetadata(metadata.ToArray());
        }

        public LiteralSqlStatementBuilder AddMetadata(params ModelFramework.Common.Builders.MetadataBuilder[] metadata)
        {
            Metadata.AddRange(metadata);
            return this;
        }

        public LiteralSqlStatementBuilder AddMetadata(string name, object? value)
        {
            AddMetadata(new ModelFramework.Common.Builders.MetadataBuilder().WithName(name).WithValue(value));
            return this;
        }

        public LiteralSqlStatementBuilder()
        {
            Metadata = new System.Collections.Generic.List<ModelFramework.Common.Builders.MetadataBuilder>();
            #pragma warning disable CS8603 // Possible null reference return.
            _statementDelegate = new (() => new System.Text.StringBuilder());
            #pragma warning restore CS8603 // Possible null reference return.
        }

        public LiteralSqlStatementBuilder(ModelFramework.Database.SqlStatements.LiteralSqlStatement source)
        {
            Metadata = new System.Collections.Generic.List<ModelFramework.Common.Builders.MetadataBuilder>();
            _statementDelegate = new (() => new System.Text.StringBuilder(source.Statement));
            Metadata.AddRange(source.Metadata.Select(x => new ModelFramework.Common.Builders.MetadataBuilder(x)));
        }

        protected System.Lazy<System.Text.StringBuilder> _statementDelegate;
    }
#nullable restore
}

